name: Pipeline for automatic model creation

on:
  push:

jobs:
  create-models:
    runs-on: arc-runner-set

    steps:
      - run: sudo apt-get install libgomp1 wkhtmltopdf
      - run: echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install pipx
        run: python3 -m pip install --user pipx

      - name: Install poetry (project manager)
        run: pipx install poetry --python 3.11

      - name: Configure poetry
        run: poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install

      - name: Learn Models
        run: python3 -m asi_labs.lab3.learn

      - name: Create Dataset Profile
        run: python3 -m asi_labs.lab3.dataset

      - name: Copy reports to /tmp
        run: |
          mkdir -p /tmp/reports
          cp .models/report.pdf .models/report.html .models/*.png .assets/CollegeDistance.html /tmp/reports

      - name: Archive generated reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            /tmp/reports

      - name: Copy model to /tmp
        run: |
          mkdir -p /tmp/model
          cp .models/output_model.pkl /tmp/model

      - name: Archive generated models
        uses: actions/upload-artifact@v4
        with:
          name: model
          path: /tmp/model
