on:
  push:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Echo
        run: echo "Hello, world!"

  create-model:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install poetry (project manager)
        run: pipx install poetry --python 3.12

      - name: Configure poetry
        run: poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install
